apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: assbot
    namespace: assbot
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: assbot
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: assbot
      spec:
        containers:
        - env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                key: token
                name: bot-secrets
          - name: CHANNEL
            value: "@assthread"
          - name: LOGLEVEL
            value: "INFO"
          - name: ADMIN
            value: "konata04"
          image: ghcr.io/tsunamaru/assbot/ci-build:latest
          imagePullPolicy: Always
          name: bot
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 5
kind: List
metadata: {}
