name: Base image update

on:
  schedule:
    - cron: '0 0 1 * *'

env:
  BASE_IMAGE_NAME: base

jobs:
  base-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['x86_64']
  
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build base image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/$BASE_IMAGE_NAME:latest
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE . --push -f build/base.Dockerfile